export const products = [
  {
    id: 1,
    slug: "majestic-pure-lavender-essential-oil",
    name: "Majestic Pure Lavender Essential Oil",
    price: "$8.49",
    rating: 4.6,
    reviews: 1247,
    image: "https://m.media-amazon.com/images/I/51ETDA1Y2UL._SY741_.jpg",
    description:
      "Majestic Pure Lavender Oil is a blend of two pure lavender oils from Bulgaria and France, steam distilled and therapeutic grade, packaged in the USA. It offers a rich floral scent helpful in soothing the mind and body when used in aromatherapy.",
    benefits: [
      "Soothes the mind and body in aromatherapy with its rich floral aroma",
      "Blends well with almost any other essence, becoming more flowery as it evolves",
      "Pure and undiluted for therapeutic use in diffusers, aromatherapy, soap, and candle making",
      "Includes a premium quality glass dropper for ease of use",
    ],
    ingredients: "Blend of Lavandula angustifolia from Bulgaria and Lavandula hybrida from France",
    usage:
      "For external use only; dilute with a carrier oil other than aromatherapy; test for allergic reaction on inside of elbow before topical use.",
    amazonUrl: "https://www.amazon.com/Majestic-Pure-Lavender-Therapeutic-Essential/dp/B00TSTZQEY/",
  },
  {
    id: 2,
    slug: "waxcanpy-scented-candles",
    name: "Waxcanpy Scented Candles",
    price: "$19.99",
    rating: 4.8,
    reviews: 456,
    image: "https://m.media-amazon.com/images/I/71MByypw7TL._AC_SX679_.jpg",
    description:
      "Hand-poured scented candles designed for aromatherapy and relaxation, infused with natural essential oils to create a calming atmosphere in your home.",
    benefits: ["Long-lasting burn time", "Natural soy wax", "Aromatherapy benefits", "Relaxing scents"],
    ingredients: "Soy Wax, Essential Oils, Cotton Wick",
    usage: "Light the candle and let it burn for 2-3 hours at a time. Trim wick before each use.",
    amazonUrl: "https://www.amazon.com/Waxcanpy-Scented-Candles-Aromatherapy-Relaxing/dp/B0FJD6WK4X/",
  },
  {
    id: 3,
    slug: "nighttime-magnesium-lotion",
    name: "Nighttime Magnesium Lotion with Arnica",
    price: "$22.99",
    rating: 4.7,
    reviews: 789,
    image: "https://m.media-amazon.com/images/I/71+oszjnRVL._SX466_.jpg",
    description:
      "A soothing nighttime lotion enriched with magnesium and arnica to promote relaxation and ease muscle tension for better sleep.",
    benefits: ["Supports restful sleep", "Relieves muscle soreness", "Skin-friendly formula", "Quick absorption"],
    ingredients: "Magnesium, Arnica Extract, Natural Oils",
    usage: "Apply a generous amount to clean skin before bedtime and massage gently.",
    amazonUrl: "https://www.amazon.com/Nighttime-Magnesium-Lotion-Arnica-Skin-Friendly/dp/B0F1QHNFJP/",
  },
  {
    id: 4,
    slug: "young-living-stress-away",
    name: "Young Living Stress Away Essential Oil",
    price: "$28.99",
    rating: 4.9,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/61J1LGMzEtL._AC_SY879_.jpg",
    description:
      "A proprietary blend of essential oils designed to help manage stress and promote a sense of well-being throughout the day.",
    benefits: ["Reduces stress", "Uplifting aroma", "Portable roll-on", "Therapeutic grade"],
    ingredients: "Lavender, Cedarwood, Copaiba, Vanilla",
    usage: "Apply to wrists or neck as needed for instant calm.",
    amazonUrl: "https://www.amazon.com/Stress-Away-Young-Living-Essential/dp/B00J4F7W12/",
  },
  {
    id: 5,
    slug: "nurture-nature-lavender-oil",
    name: "Nurture Nature Lavender Essential Oil",
    price: "$15.99",
    rating: 4.8,
    reviews: 567,
    image: "https://m.media-amazon.com/images/I/8159VV0u7tL._SX466_.jpg",
    description:
      "Pure lavender essential oil crafted for mothers and wellness enthusiasts, perfect for daily relaxation rituals.",
    benefits: ["Promotes calm", "Versatile for diffusers", "Natural and pure", "Supports self-care"],
    ingredients: "100% Pure Lavender Oil",
    usage: "Diffuse or apply topically diluted with a carrier oil.",
    amazonUrl: "https://www.amazon.com/Nurture-Nature-Essential-Lavender-Mothers/dp/B09LHZHTNH",
  },
  {
    id: 6,
    slug: "naturobliss-lavender-roll-on",
    name: "NaturoBliss Lavender Essential Oil Roll On",
    price: "$6.99",
    rating: 4.5,
    reviews: 61412,
    image: "https://m.media-amazon.com/images/I/51a1v0QbHzL._AC_SX679_.jpg",
    description:
      "Premium lavender essential oil that is 100% pure, gentle, and effective for natural relaxation and tranquility. It is blended with carrier oils for easy topical application and comes in a TSA-approved size for travel and daily use.",
    benefits: [
      "Promotes relaxation and a sense of tranquility with its soothing scent",
      "Enhances bedtime routines by applying behind the ears or on the neck for a calming aroma",
      "Allows relaxation anywhere by applying to wrists or neck for on-the-go use",
      "Supports aromatherapy and sleep aid through its natural, undiluted properties",
    ],
    ingredients: "Lavender oil, MCT",
    usage: "Topical use only: Apply 1-2 drops behind ears, on neck, or wrists. Perform a patch test before use.",
    amazonUrl: "https://www.amazon.com/NaturoBliss-Lavender-Essential-Oil-Roll/dp/B0DQJ5HCVS/",
  },
  {
    id: 7,
    slug: "ultrasonic-essential-humidifier",
    name: "Ultrasonic Essential Oil Diffuser with Himalayan Salt",
    price: "$29.99",
    rating: 4.6,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71+Q1YMyleL._AC_SX679_.jpg",
    description:
      "A stylish ultrasonic humidifier that doubles as an aromatherapy diffuser, featuring Himalayan salt for added wellness benefits.",
    benefits: ["Humidifies air", "Diffuses essential oils", "Aesthetic design", "Quiet operation"],
    ingredients: "Plastic, Himalayan Salt Lamp",
    usage: "Add water and essential oils, then turn on for mist and light therapy.",
    amazonUrl: "https://www.amazon.com/Ultrasonic-Essential-Himalayan-Aromatherapy-Humidifier/dp/B0DV3MYV3Z/",
  },
  {
    id: 8,
    slug: "now-peaceful-sleep-oil",
    name: "NOW Essential Oils Peaceful Sleep Blend",
    price: "$12.99",
    rating: 4.7,
    reviews: 890,
    image: "https://m.media-amazon.com/images/I/61O4SP2gg9L._AC_SX679_.jpg",
    description:
      "A relaxing blend of essential oils crafted to support a restful night's sleep and ease into tranquility.",
    benefits: ["Promotes relaxation", "Supports sleep", "Pure blend", "Aromatherapy ready"],
    ingredients: "Lavender, Cedarwood, Ylang Ylang",
    usage: "Diffuse or apply diluted topically before bed.",
    amazonUrl: "https://www.amazon.com/NOW-Essential-Peaceful-Relaxing-Aromatherapy/dp/B00GWZ0AWU",
  },
  {
    id: 9,
    slug: "now-lavender-essential-oil",
    name: "NOW Essential Oils Lavender Oil",
    price: "$9.99",
    rating: 4.8,
    reviews: 3456,
    image: "https://m.media-amazon.com/images/I/71pHLvEz4mL._AC_SX679_.jpg",
    description:
      "Steam-distilled lavender essential oil, verified for purity, ideal for aromatherapy and daily wellness.",
    benefits: ["Calming scent", "Versatile use", "High quality", "Therapeutic grade"],
    ingredients: "Lavandula Officinalis (Lavender) Oil",
    usage: "Add to diffuser or carrier oil for massage.",
    amazonUrl: "https://www.amazon.com/Now-Essential-Verified-Distilled-Aromatherapy/dp/B08MC611V7/",
  },
  {
    id: 10,
    slug: "innogear-aromatherapy-diffuser",
    name: "InnoGear Ultrasonic Aromatherapy Diffuser",
    price: "$24.99",
    rating: 4.7,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/819yNDo0IgL._AC_SX679_.jpg",
    description:
      "Compact ultrasonic humidifier and essential oil diffuser for creating a serene environment at home or office.",
    benefits: ["7 color lights", "Auto shut-off", "Quiet operation", "Large capacity"],
    ingredients: "PP Plastic",
    usage: "Fill with water, add oils, and select mist mode.",
    amazonUrl: "https://www.amazon.com/InnoGear-Aromatherapy-Essential-Ultrasonic-Humidifier/dp/B0BNN3MRJP/",
  },
  {
    id: 11,
    slug: "bath-body-works-lavender-lotion",
    name: "Bath & Body Works Aromatherapy Lavender Lotion",
    price: "$13.00",
    rating: 4.6,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/81GGQ1vJAvL._SY679_.jpg",
    description: "Ultra-creamy body lotion infused with lavender essential oil to soothe and calm the senses.",
    benefits: ["Deep hydration", "Relaxing fragrance", "Fast absorbing", "Daily use"],
    ingredients: "Lavender Essential Oil, Shea Butter",
    usage: "Apply generously to skin after bathing.",
    amazonUrl: "https://www.amazon.com/Bath-Body-Works-Aromatherapy-Lavender/dp/B00KRLCWIA/",
  },
  {
    id: 12,
    slug: "comfheat-lavender-eye-mask",
    name: "Comfheat Lavender Filled Eye Mask",
    price: "$16.99",
    rating: 4.5,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/61V4qLf3y-L._AC_SX679_.jpg",
    description: "Microwavable and freezable eye mask filled with lavender for headache relief and better sleep.",
    benefits: ["Hot/cold therapy", "Aromatherapy", "Adjustable strap", "Washable cover"],
    ingredients: "Flaxseed, Lavender",
    usage: "Microwave for warm therapy or freeze for cold relief.",
    amazonUrl: "https://www.amazon.com/Comfheat-Lavender-Sleeping-Microwavable-Compression/dp/B09V14GHMV/",
  },
  {
    id: 13,
    slug: "plant-therapy-lavender-oil",
    name: "Plant Therapy Lavender Essential Oil",
    price: "$11.99",
    rating: 4.9,
    reviews: 4567,
    image: "https://m.media-amazon.com/images/I/519nYhNT+GL._AC_SX679_.jpg",
    description: "High-quality, therapeutic grade lavender oil for aromatherapy and topical use.",
    benefits: ["Pure and natural", "Kid-safe", "GC/MS tested", "Versatile"],
    ingredients: "Lavandula Angustifolia Oil",
    usage: "Diffuse 3-4 drops or dilute for skin application.",
    amazonUrl: "https://www.amazon.com/Plant-Therapy-Aromatherapy-Therapeutic-milliliter/dp/B007P70UKQ/",
  },
  {
    id: 14,
    slug: "bath-body-works-eucalyptus-lotion",
    name: "Bath & Body Works Aromatherapy Eucalyptus Lotion",
    price: "$13.00",
    rating: 4.7,
    reviews: 3456,
    image: "https://m.media-amazon.com/images/I/61a62QIg52L._SY679_.jpg",
    description: "Body lotion with eucalyptus and spearmint to refresh and soothe stressed skin.",
    benefits: ["Invigorating scent", "Moisturizing", "Stress relief", "Silky feel"],
    ingredients: "Eucalyptus Essential Oil, Spearmint",
    usage: "Smooth over body from shoulders to toes.",
    amazonUrl: "https://www.amazon.com/Bath-Body-Works-Aromatherapy-Stress/dp/B00D1441JS/",
  },
  {
    id: 15,
    slug: "woolzies-lavender-oil",
    name: "Woolzies Lavender Essential Oil",
    price: "$9.99",
    rating: 4.6,
    reviews: 789,
    image: "https://m.media-amazon.com/images/I/615wFLz+zaL._SX466_.jpg",
    description: "Undiluted therapeutic lavender oil to help with insomnia and promote restful sleep.",
    benefits: ["Aids sleep", "Pure formula", "Affordable", "Multi-use"],
    ingredients: "Lavandula Officinalis Oil",
    usage: "Inhale directly or dilute for massage.",
    amazonUrl: "https://www.amazon.com/Woolzies-Essential-Insomnia-Undiluted-Therapeutic/dp/B07VZY9D5M/",
  },
  {
    id: 16,
    slug: "sheamoisture-lavender-massage-oil",
    name: "SheaMoisture Lavender & Orchid Massage Oil",
    price: "$9.99",
    rating: 4.5,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71ibCAsy3UL._SX466_.jpg",
    description: "Nourishing massage oil with shea butter and essential oils for silky smooth skin.",
    benefits: ["Deep hydration", "Relaxing aroma", "Paraben-free", "For all skin types"],
    ingredients: "Shea Butter, Lavender Oil, Orchid Extract",
    usage: "Warm between hands and massage into skin.",
    amazonUrl: "https://www.amazon.com/SheaMoisture-Lavender-Orchid-Massage-Ounce/dp/B005C2NA4E/",
  },
  {
    id: 17,
    slug: "naturals-lavender-shower-steamers",
    name: "Naturals Lavender Shower Steamers",
    price: "$12.99",
    rating: 4.7,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/91FAZ-zqdML._SX466_.jpg",
    description: "Effervescent shower tablets infused with lavender for a spa-like aromatherapy experience.",
    benefits: ["Quick relaxation", "Easy to use", "Strong scent", "Travel-friendly"],
    ingredients: "Baking Soda, Citric Acid, Lavender Oil",
    usage: "Place on shower floor and let steam activate.",
    amazonUrl: "https://www.amazon.com/Naturals-Shower-Steamers-tablet-Lavender/dp/B0CZ4G14P6/",
  },
  {
    id: 18,
    slug: "thisworks-deep-sleep-cocoon",
    name: "THISWORKS Deep Sleep Body Cocoon",
    price: "$38.00",
    rating: 4.6,
    reviews: 567,
    image: "https://m.media-amazon.com/images/I/71iBlT-QtxL._SX466_.jpg",
    description:
      "A multi-tasker for the mind and body, use deep sleep body cocoon each night before bed to help restore calm to the mind. Including a unique Superblend of Shea Butter, Camelia and Satvia oils to help nourish the skin and preserve the skin’s barrier alongside our original Deep Sleep fragrance to help improve sleep quality.",
    benefits: [
      "Calming Aromatherapy for Better Sleep: Infused with a powerful blend of Lavender, Vetivert, and Camomile to help calm your mind and body - ideal for bedtime relaxation and restful sleep",
      "Deeply Nourishing Overnight Moisturizer: A light, fast-absorbing cream that hydrates and softens skin while you sleep - perfect for restoring dry, stressed, or tired skin overnight",
      "Sleep-Supporting Functional Fragrance: Part of the award-winning Deep Sleep range, trusted by millions to improve sleep quality through science-backed Functional Fragrance technology",
      "Travel-Friendly & Perfect for Wind-Down Routine: Compact 100ml tube is ideal for travel or bedside use. Add to your nighttime ritual for a sensorial wind-down that prepares you for quality rest",
    ],
    ingredients:
      "Aqua (Water/Eau), Glycerin, Caprylic/Capric Triglyceride, Stearic Acid, Ricinus Communis (Castor) Seed Oil, Butyrospermum Parkii (Shea) Butter, Ethylhexyl Palmitate, Coconut Alkanes, Cetearyl Olivate, Crambe Abyssinica Seed Oil, Phenoxyethanol, Sorbitan Olivate, Galactoarabinan, Parfum (Fragrance), Hydrogenated Castor Oil, Linalool*, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Coco-Caprylate/Caprate, Benzyl Alcohol, Cera Alba (Beeswax/Cire d'abeille), Sodium Hydroxide, Camelina Sativa Seed Oil, Disodium EDTA, Ethylhexylglycerin, Copernicia Cerifera (Carnauba/Cire de carnauba) Wax, Cinnamomum Camphora (Camphor) Leaf Oil, Lavandula Angustifolia (Lavender) Oil, Ormenis Multicaulis (Chamomile) Flower Extract, Pogostemon Cablin (Patchouli) Oil, Vetiveria Zizanoides (Vetivert) Root Oil, Dehydroacetic Acid, Geraniol*, Limonene*, Citric Acid",
    usage: "Massage into skin all over the body each night before bed to help restore and nourish the skin and mind.",
    amazonUrl: "https://www.amazon.com/THISWORKS-Deep-Sleep-Body-Cocoon/dp/B083F9X9CT/",
  },
  {
    id: 19,
    slug: "peppermint-essential-oil-diffuser",
    name: "Peppermint Essential Oil for Diffuser",
    price: "$14.99",
    rating: 4.8,
    reviews: 890,
    image: "https://m.media-amazon.com/images/I/61hgdS24cmL._AC_SY879_.jpg",
    description:
      "Invigorating peppermint essential oil perfect for humidifiers and aromatherapy to boost energy and clear sinuses.",
    benefits: ["Energizing aroma", "Respiratory support", "Pure therapeutic", "Multi-purpose"],
    ingredients: "Mentha Piperita Oil",
    usage: "Add 5 drops to diffuser water for refreshing mist.",
    amazonUrl: "https://www.amazon.com/Essential-PEPPERMINT-Therapeutic-Humidifier-Aromatherapy/dp/B084SWC7SF/",
  },
  {
    id: 20,
    slug: "lavender-eye-pillow-relaxation",
    name: "Lavender Eye Pillow for Relaxation",
    price: "$18.99",
    rating: 4.6,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/61OGxeWGe-L._AC_SX679_.jpg",
    description:
      "Removable lavender-filled eye pillow designed for meditation, headache relief, and restorative sleep.",
    benefits: ["Blocks light", "Aromatherapy", "Weighted comfort", "Easy to clean"],
    ingredients: "Flax Seeds, Lavender Flowers",
    usage: "Place over eyes during rest or meditation sessions.",
    amazonUrl: "https://www.amazon.com/Lavender-Relaxation-Meditation-Headache-Removable/dp/B07N82GNFS/",
  },
  {
    id: 21,
    slug: "frida-baby-lavender-bath-soak",
    name: "Frida Baby Lavender Essential Bath Soak",
    price: "$12.99",
    rating: 4.7,
    reviews: 456,
    image: "https://m.media-amazon.com/images/I/7143iz3KK4L._SX466_.jpg",
    description: "Gentle bath soak with lavender for babies, providing calming aromatherapy during bath time.",
    benefits: ["Soothes baby skin", "Relaxing scent", "Tear-free", "Natural ingredients"],
    ingredients: "Lavender Oil, Epsom Salt",
    usage: "Dissolve in warm bath water for soothing soak.",
    amazonUrl: "https://www.amazon.com/Frida-Baby-Lavender-Essential-Aromatherapy/dp/B08BSMWMH1/",
  },
  {
    id: 22,
    slug: "relaxcoo-meditation-eye-mask",
    name: "RelaxCoo Lavender Eye Mask for Meditation",
    price: "$15.99",
    rating: 4.5,
    reviews: 789,
    image: "https://m.media-amazon.com/images/I/81oF8wLcwnL._AC_SX679_.jpg",
    description: "Aromatherapy eye mask accessory to enhance relaxation and meditation practices with lavender scent.",
    benefits: ["Promotes mindfulness", "Light blocking", "Portable", "Reusable"],
    ingredients: "Silk, Lavender, Chamomile",
    usage: "Wear during yoga or meditation for deeper focus.",
    amazonUrl: "https://www.amazon.com/RelaxCoo-Relaxation-Meditation-Accessories-Aromatherapy/dp/B0BR27WWGK/",
  },
  {
    id: 23,
    slug: "porseme-ultrasonic-humidifier",
    name: "Porseme Essential Oil Diffuser Humidifier",
    price: "$26.99",
    rating: 4.6,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71KaOUySKfL._AC_SX679_.jpg",
    description: "Modern ultrasonic humidifier for essential oils, creating a misty aromatherapy environment.",
    benefits: ["Color-changing lights", "Large tank", "Safe for kids", "Easy clean"],
    ingredients: "ABS Plastic",
    usage: "Add water and oils, plug in and enjoy the mist.",
    amazonUrl: "https://www.amazon.com/Porseme-Essential-Aromatherapy-Ultrasonic-Humidifier/dp/B0DHKKFQKR/",
  },
  {
    id: 24,
    slug: "vicks-purezzzs-melatonin-gummies",
    name: "Vicks PureZzzs Melatonin Sleep Gummies",
    price: "$11.99",
    rating: 4.4,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/7129sag1N7L._AC_SX679_.jpg",
    description: "Sleep aid gummies with melatonin, chamomile, lavender, and valerian for natural rest.",
    benefits: ["Fast-acting sleep support", "Natural flavors", "Non-habit forming", "Vegan"],
    ingredients: "Melatonin, Chamomile, Lavender, Valerian Root",
    usage: "Take 1-2 gummies 30 minutes before bed.",
    amazonUrl: "https://www.amazon.com/Vicks-Melatonin-Chamomile-Lavender-Valerian/dp/B07N46LTJJ/",
  },
  {
    id: 25,
    slug: "weighted-lavender-eye-mask",
    name: "Weighted Lavender Eye Mask for Sleep",
    price: "$19.99",
    rating: 4.7,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71BDWJbo9sL._AC_SX679_.jpg",
    description: "Therapeutic weighted eye mask filled with lavender to alleviate headaches and migraines.",
    benefits: ["Gentle pressure", "Aromatherapy relief", "Cooling option", "Adjustable"],
    ingredients: "Clay Beads, Lavender",
    usage: "Place over eyes for 10-15 minutes for relief.",
    amazonUrl: "https://www.amazon.com/Weighted-Lavender-Sleeping-Headache-Migraine/dp/B08RN6XZN3",
  },
  {
    id: 26,
    slug: "essential-oil-bath-salts",
    name: "Essential Oil Infused Bath Salts",
    price: "$14.99",
    rating: 4.6,
    reviews: 890,
    image: "https://m.media-amazon.com/images/I/61zmN9Q3XuL._AC_SX679_.jpg",
    description: "Relaxing bath salts with natural essential oils and lemongrass for detoxification and calm.",
    benefits: ["Muscle relaxation", "Skin softening", "Aromatherapy", "Epsom salt base"],
    ingredients: "Epsom Salt, Sea Salt, Lemongrass Oil",
    usage: "Add 1-2 cups to running bath water.",
    amazonUrl: "https://www.amazon.com/Salts-Natural-Essential-Lemongrass-21-16/dp/B075YRLSDG/",
  },
  {
    id: 27,
    slug: "dream-essential-oil-blend",
    name: "Dream Essential Oil Blend",
    price: "$16.99",
    rating: 4.8,
    reviews: 456,
    image: "https://m.media-amazon.com/images/I/71o-xx5QchL._AC_SX679_.jpg",
    description: "Therapeutic blend of oils to induce dreams and enhance sleep quality through aromatherapy.",
    benefits: ["Vivid dreaming", "Deep relaxation", "Natural sleep aid", "Pure blend"],
    ingredients: "Lavender, Mugwort, Clary Sage",
    usage: "Diffuse overnight or apply to temples.",
    amazonUrl: "https://www.amazon.com/Dream-Essential-Oil-Therapeutic-Aromatherapy/dp/B08FRR82WP/",
  },
  {
    id: 28,
    slug: "essential-oil-flame-diffuser",
    name: "Essential Oil Diffuser with Flame Effect",
    price: "$32.99",
    rating: 4.7,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/61HAJlDo1EL._AC_SX679_.jpg",
    description: "250ml capacity diffuser with realistic flame simulation for safe, flameless aromatherapy.",
    benefits: ["Ambient lighting", "No open flame", "Large water tank", "Remote control"],
    ingredients: "Glass, LED Lights",
    usage: "Fill with water and oils, select flame mode.",
    amazonUrl: "https://www.amazon.com/Eseential-Oil-Diffuser-250ml-Flame/dp/B0DCRSNJ8L/",
  },
  {
    id: 29,
    slug: "affirmation-lavender-candle",
    name: "Words of Affirmation Lavender Candle",
    price: "$24.99",
    rating: 4.9,
    reviews: 567,
    image: "https://m.media-amazon.com/images/I/611-trjtFKL._AC_SX679_PIbundle-3,TopRight,0,0_SH20_.jpg",
    description:
      "Scented candle with wooden wick and essential oils, paired with positive affirmations for mindfulness.",
    benefits: ["Crackling wick sound", "Long burn time", "Inspirational", "Soy wax"],
    ingredients: "Soy Wax, Lavender Oil, Wooden Wick",
    usage: "Light during meditation and read affirmations.",
    amazonUrl: "https://www.amazon.com/Words-Affirmation-Candle-Wooden-Essential/dp/B0B4DJW4XH/",
  },
  {
    id: 30,
    slug: "natrol-melatonin-gummies",
    name: "Natrol Melatonin 10mg Gummies",
    price: "$9.99",
    rating: 4.5,
    reviews: 7890,
    image: "https://m.media-amazon.com/images/I/710yu6FlQ7L._AC_SX679_.jpg",
    description: "Strawberry-flavored melatonin gummies to help you fall asleep faster and stay asleep longer.",
    benefits: ["Quick dissolve", "No grogginess", "Vegan", "High potency"],
    ingredients: "Melatonin, Pectin, Natural Flavors",
    usage: "Chew 1 gummy 30-60 minutes before bed.",
    amazonUrl: "https://www.amazon.com/Natrol-Melatonin-10Mg-Gummy-Count/dp/B079TD7HG2/",
  },
  {
    id: 31,
    slug: "happy-wraps-microwavable-pack",
    name: "Happy Wraps Microwavable Aromatherapy Pack",
    price: "$17.99",
    rating: 4.6,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71Nn5gBuPML._AC_SX679_.jpg",
    description: "Versatile heat pack for migraines and tension relief, infused with calming herbs.",
    benefits: ["Hot/cold therapy", "Targeted relief", "Portable", "Natural filling"],
    ingredients: "Rice, Lavender, Chamomile",
    usage: "Heat in microwave for 1-2 minutes for warm therapy.",
    amazonUrl: "https://www.amazon.com/Happy-Wraps-Microwavable-Aromatherapy-Migraines/dp/B07NCQCVC8/",
  },
  {
    id: 32,
    slug: "hem-lavender-backflow-cones",
    name: "HEM Lavender Backflow Incense Cones",
    price: "$5.99",
    rating: 4.5,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/51gHwRdAfeL._AC_SX679_.jpg",
    description:
      "HEM Lavender Backflow Incense Cones provide a long-lasting floral aroma designed for positivity, relaxation, and sleep. They are made with wood powder for aromatherapy benefits including stress relief and air purification.",
    benefits: [
      "Promotes positivity and relaxation through its floral lavender scent",
      "Aids in better sleep with long-lasting aroma",
      "Supports stress relief via wood powder aromatherapy",
      "Helps with air purification",
    ],
    ingredients: "Wood powder",
    usage: "Use with backflow incense burner for cascading smoke effect.",
    amazonUrl: "https://www.amazon.com/HEM-Back-Flow-Cones-Lavender/dp/B0856SYLXB/",
  },
  {
    id: 33,
    slug: "natures-truth-good-nite-oil",
    name: "Nature's Truth Good Nite Essential Oil",
    price: "$7.69",
    rating: 4.7,
    reviews: 456,
    image: "https://m.media-amazon.com/images/I/7174gyCaZ+L._AC_SY879_.jpg",
    description:
      "This is a pure essential oil designed for aromatherapy, featuring a botanical blend that is plant-based, non-GMO, and gluten-free. It comes in a 15 mL size (0.51 Fl Oz) with a clear color.",
    benefits: [
      "Supports aromatherapy practices for relaxation",
      "Made from plant-based ingredients",
      "Non-GMO formulation",
      "Gluten-free for dietary compatibility",
    ],
    ingredients: "Botanical Blend Essential Oils",
    usage: "Diffuse or inhale for bedtime relaxation.",
    amazonUrl: "https://www.amazon.com/Natures-Truth-Essential-Fluid-Ounce/dp/B01APTZDAW/",
  },
  {
    id: 34,
    slug: "bodyrestore-shower-steamers",
    name: "BodyRestore Aromatherapy Shower Steamers",
    price: "$13.99",
    rating: 4.6,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/71pb+JOaCHL._AC_SX679_.jpg",
    description: "Pack of shower steamers with essential oils for a luxurious, spa-inspired shower experience.",
    benefits: ["Instant aromatherapy", "Variety of scents", "Fizzing action", "Gift ready"],
    ingredients: "Sodium Bicarbonate, Citric Acid, Essential Oils",
    usage: "Unwrap and place in shower away from direct water.",
    amazonUrl: "https://www.amazon.com/BodyRestore-Shower-Steamers-Aromatherapy-Packs/dp/B0BJYCRS51/",
  },
  {
    id: 35,
    slug: "asakuki-essential-diffuser",
    name: "ASAKUKI Ultrasonic Essential Oil Diffuser",
    price: "$21.99",
    rating: 4.7,
    reviews: 7890,
    image: "https://m.media-amazon.com/images/I/61KskoaRxpL._AC_SX679_.jpg",
    description: "Premium aromatherapy humidifier with large capacity for continuous mist and scent diffusion.",
    benefits: ["4 timer settings", "LED lights", "Whisper quiet", "Easy to clean"],
    ingredients: "PP Material",
    usage: "Add 300ml water and 8-10 drops of oil.",
    amazonUrl: "https://www.amazon.com/ASAKUKI-Essential-Ultrasonic-Aromatherapy-Humidifier/dp/B01MR4Y0CZ/",
  },
  {
    id: 36,
    slug: "eucalyptus-shower-steamers",
    name: "Eucalyptus & Watermelon Shower Steamers",
    price: "$11.99",
    rating: 4.5,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71vm5cfg4TL._AC_SX679_.jpg",
    description: "Refreshing shower steamers with eucalyptus and watermelon scents for sinus relief and invigoration.",
    benefits: ["Clears congestion", "Uplifting aroma", "Moisturizing", "Pack of 10"],
    ingredients: "Baking Soda, Essential Oils",
    usage: "Place on shower ledge and inhale the steam.",
    amazonUrl: "https://www.amazon.com/Shower-Steamers-Aromatherapy-Eucalyptus-Watermelon/dp/B0BFHXRG1F/",
  },
  {
    id: 37,
    slug: "bath-body-works-sleep-spray",
    name: "Bath & Body Works Aromatherapy Sleep Spray",
    price: "$14.00",
    rating: 4.8,
    reviews: 3456,
    image: "https://m.media-amazon.com/images/I/61XD7NG7BeL._SX466_.jpg",
    description: "Pillow mist with lavender and vanilla to promote tranquility and restful sleep.",
    benefits: ["Quick spray application", "Calming blend", "Long-lasting scent", "Non-aerosol"],
    ingredients: "Lavender Essential Oil, Vanilla",
    usage: "Spritz on pillows and linens before bed.",
    amazonUrl: "https://www.amazon.com/Bath-Body-Works-Aromatherapy-Sleep/dp/B00UM3SENA/",
  },
  {
    id: 38,
    slug: "lagunamoon-essential-oil-set",
    name: "Lagunamoon Essential Oils Diffuser Set",
    price: "$19.99",
    rating: 4.6,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/81A3ShNaVIL._SX466_.jpg",
    description: "Top 6 essential oils set with diffuser for comprehensive aromatherapy needs.",
    benefits: ["Variety pack", "Pure oils", "Compact diffuser", "Beginner friendly"],
    ingredients: "Multiple Essential Oils",
    usage: "Use individually in the included diffuser.",
    amazonUrl: "https://www.amazon.com/Lagunamoon-Essential-Diffuser-Humidifier-Aromatherapy/dp/B06XRLR9RQ/",
  },
  {
    id: 39,
    slug: "body-restore-bath-bombs",
    name: "Body Restore Aromatherapy Bath Bombs",
    price: "$16.99",
    rating: 4.7,
    reviews: 4567,
    image: "https://m.media-amazon.com/images/I/712GQHu5BeL._AC_SX679_.jpg",
    description: "Fizzy bath bombs infused with essential oils for ultimate relaxation and skin care.",
    benefits: ["Rich lather", "Moisturizing butters", "Stress relief", "Colorful fizz"],
    ingredients: "Baking Soda, Citric Acid, Oils",
    usage: "Drop into warm bath and soak.",
    amazonUrl: "https://www.amazon.com/Body-Restore-Bath-Bombs-Aromatherapy/dp/B08FDCLXNP/",
  },
  {
    id: 40,
    slug: "edens-garden-lavender-oil",
    name: "Edens Garden Lavender Essential Oil",
    price: "$10.99",
    rating: 4.9,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/61lWodlSLqL._AC_SX679_.jpg",
    description: "Therapeutic grade lavender oil for aromatherapy, sourced sustainably for purity.",
    benefits: ["Calms nerves", "Skin soothing", "Sleep support", "Lab tested"],
    ingredients: "Lavandula Angustifolia",
    usage: "Diffuse 5 drops for room scenting.",
    amazonUrl: "https://www.amazon.com/Edens-Garden-Essential-Therapeutic-Aromatherapy/dp/B00I9L4BTI/",
  },
  {
    id: 41,
    slug: "victorias-lavender-heat-pack",
    name: "Victoria's Lavender Microwavable Heat Pack",
    price: "$20.99",
    rating: 4.6,
    reviews: 789,
    image: "https://m.media-amazon.com/images/I/81wknc-WimL._AC_SX679_PIbundle-2,TopRight,0,0_SH20_.jpg",
    description: "Aromatherapy essential oil filled pack for soothing aches and promoting relaxation.",
    benefits: ["Versatile shape", "Natural heat retention", "Lavender scent", "Giftable"],
    ingredients: "Cherry Pits, Lavender",
    usage: "Microwave and apply to sore areas.",
    amazonUrl: "https://www.amazon.com/Victorias-Lavender-Microwavable-Aromatherapy-Essential/dp/B0CK4SVYNR/",
  },
  {
    id: 42,
    slug: "fall-relaxation-shower-steamers",
    name: "Fall Relaxation Aromatherapy Shower Steamers",
    price: "$12.99",
    rating: 4.5,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/716A8KnZ7HL._SX466_.jpg",
    description: "Seasonal shower steamers with relaxing scents for autumn self-care and gifting.",
    benefits: ["Cozy aromas", "Easy fizz", "Stress busting", "Set of 8"],
    ingredients: "Essential Oils Blend",
    usage: "Activate in shower for aromatic steam.",
    amazonUrl: "https://www.amazon.com/Shower-Steamers-Aromatherapy-Fall-Relaxation-Gift/dp/B0FMSJSVJY/",
  },
  {
    id: 43,
    slug: "eucalyptus-shower-steamers-set",
    name: "Eucalyptus Shower Steamers for Congestion",
    price: "$13.99",
    rating: 4.7,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71yVm5yQMBL._SX466_.jpg",
    description: "Therapeutic shower steamers to relieve congestion and promote relaxation with eucalyptus.",
    benefits: ["Sinus clearing", "Spa feel", "Long-lasting", "Natural"],
    ingredients: "Eucalyptus Oil, Menthol",
    usage: "Place in shower and let hot water dissolve.",
    amazonUrl: "https://www.amazon.com/Eucalyptus-Congestion-Relaxation-Therapeutic-Aromatherapy/dp/B09CSG5PJ7/",
  },
  {
    id: 44,
    slug: "dr-teals-sleep-bath",
    name: "Dr Teal's Sleep Soak with Melatonin",
    price: "$7.99",
    rating: 4.6,
    reviews: 4567,
    image: "https://m.media-amazon.com/images/I/81Sy5O5MxZL._SX466_.jpg",
    description: "Epsom salt bath soak with melatonin and essential oils for deeper, more restorative sleep.",
    benefits: ["Muscle soak", "Sleep enhancement", "Lavender calm", "Affordable"],
    ingredients: "Magnesium Sulfate, Melatonin, Lavender",
    usage: "Pour under warm running water and soak for 20 minutes.",
    amazonUrl: "https://www.amazon.com/Dr-Teals-Sleep-Melatonin-Essential/dp/B09VH85M4Y/",
  },
  {
    id: 45,
    slug: "dr-teals-foaming-bath",
    name: "Dr Teal's Foaming Bath Soothe & Sleep",
    price: "$8.99",
    rating: 4.7,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/71ggb8jjzXL._SX466_.jpg",
    description: "Bubbly bath with lavender to unwind and prepare for a peaceful night's rest.",
    benefits: ["Rich foam", "Aromatherapy", "Skin softening", "Relaxing ritual"],
    ingredients: "Lavender Oil, Coconut Oil",
    usage: "Add to bath for luxurious bubbles.",
    amazonUrl: "https://www.amazon.com/Dr-Teals-Foaming-Soothe-Lavender/dp/B0DXKPTG92/",
  },
  {
    id: 46,
    slug: "luxury-bath-gift-set",
    name: "Luxury Bath Gift Set for Women",
    price: "$39.99",
    rating: 4.8,
    reviews: 890,
    image: "https://m.media-amazon.com/images/I/81bQDe9uXwL._SX466_.jpg",
    description: "Pampering set with frankincense and lavender products for ultimate relaxation.",
    benefits: ["Spa at home", "Multiple items", "Elegant packaging", "Self-care boost"],
    ingredients: "Frankincense Oil, Lavender",
    usage: "Use bombs, salts, and oils in sequence for full experience.",
    amazonUrl: "https://www.amazon.com/Luxury-Bath-Gift-Women-Frankincense/dp/B09SY4TJN3/",
  },
  {
    id: 47,
    slug: "thisworks-stress-manager",
    name: "thisworks Stress Manager Rollerball",
    price: "$30.00",
    rating: 4.6,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/51PYryZzjtL._SX466_.jpg",
    description: "Calming rollerball with relieving fragrance to manage daily stress on the go.",
    benefits: ["Portable relief", "Natural oils", "Quick application", "Non-greasy"],
    ingredients: "Vetivert, Eucalyptus, Basil",
    usage: "Roll on pulse points when stressed.",
    amazonUrl: "https://www.amazon.com/thisworks-Manager-Calming-Relieving-Fragrance/dp/B008GSWO8Y/",
  },
  {
    id: 48,
    slug: "edens-garden-chamomile-oil",
    name: "Edens Garden Roman Chamomile Essential Oil",
    price: "$13.99",
    rating: 4.8,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71yeX8Pq8KL._AC_SX679_.jpg",
    description: "Therapeutic chamomile oil for soothing skin and calming the mind in aromatherapy.",
    benefits: ["Anti-inflammatory", "Sleep aid", "Pure sourced", "Versatile blend"],
    ingredients: "Chamaemelum Nobile Oil",
    usage: "Dilute and apply to skin or diffuse for calm.",
    amazonUrl: "https://www.amazon.com/Edens-Garden-Essential-Therapeutic-Aromatherapy/dp/B0BJW49537/",
  },
]
